# Generated by Django 4.1 on 2022-08-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_add_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='calorie_burnout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('running', 'running'), ('walking', 'walking'), ('cycling', 'cycling')], max_length=30)),
                ('time', models.FloatField()),
                ('burn_out_calories', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='add_tag',
            name='tag',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
