# Generated by Django 4.1 on 2022-08-07 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_calorie_burnout_alter_add_tag_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_consumed', models.FloatField()),
                ('time_spend_for_acrivity', models.FloatField()),
                ('activity_for_burnout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.calorie_burnout')),
                ('food_item_consumed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.foods')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customer')),
            ],
        ),
    ]
