# Generated by Django 4.1 on 2022-08-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_customer_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_view',
            name='burnout',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
